qual_stddev: [0.1, 0.5, 1.0, 1.5, 3.0, 4.0] # Nest quality noise
threshold_stddev: 0.6 # Threshold noise
n: 500 # number of ants
threshold_mean: 4.5 # threshold
colony_reps: 30 # number of colony
base_seed: 42 # for reproducibility
recruit_strength: 0.05 # strength of recruitment
quorum_k: 20  # quorum size
quorum_sweep: [5, 10, 15, 20, 30, 40, 60, 80] # quorum sizes tested in sweep
qual_noise_fixed: 1.5 # fixed noise level used in quorum sweep plots